### ISSUE TITLE
write a script to run this parallely

### ISSUE THREAD

**Issue by Nikhil007nsg** [abhic137/Hyperledger-Fabric-k8s-gettingstarted#1]
peer chaincode invoke -o orderer:7050 --tls true --cafile $ORDERER_CA -C mychannel -n asset --peerAddresses peer0-org1:7051 --tlsRootCertFiles /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt --peerAddresses peer0-org2:7051 --tlsRootCertFiles /organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt --peerAddresses peer0-org3:7051 --tlsRootCertFiles /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt -c '{"Args":["CreateAsset","asset9","green","100","nikhil","500"]}' --waitForEvent

**Comment by abhic137** [comment]
Script is written and done . point to keep in mind ,
In Bash, when you run commands in the background using &, they are scheduled to run concurrently, but the exact timing of their execution is determined by the system scheduler. The processes spawned by the loop will be running in the background simultaneously, and their execution will overlap, giving the appearance of parallelism.

However, the exact behavior might vary depending on the system load, available resources, and other factors. The order in which the background processes start and finish is not guaranteed to be the same every time you run the script.

If you need more precise control over the execution timing, you might want to consider using parallel processing tools like GNU Parallel or xargs. These tools provide more advanced options for parallel execution and control over the number of parallel processes.
